/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
  id int,
  name char,
  date_of_birth date,
  escape_attempts int,
  neutered boolean,
  weight_kg decimal,
  PRIMARY KEY(id)
);

ALTER TABLE animals
ALTER COLUMN name TYPE varchar(100);

ALTER TABLE animals
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE animals  
  ADD COLUMN species varchar(200);

-- Create a table named owners
CREATE TABLE owners (
  id int,
  full_name varchar(100),
  age int,
  PRIMARY KEY(id)
);

-- Create a table named species
CREATE TABLE species (
  id int,
  name char(50),
  PRIMARY KEY(id)
);

ALTER TABLE owners
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE species
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE animals
DROP COLUMN species;
ALTER TABLE animals
ADD COLUMN species_id int;
ALTER TABLE animals 
ADD CONSTRAINT fk_animals 
FOREIGN KEY (species_id) 
REFERENCES species (id);
ALTER TABLE animals
ADD COLUMN owner_id int;
ALTER TABLE animals 
ADD CONSTRAINT fk_species 
FOREIGN KEY (owner_id) 
REFERENCES owners (id);
